### ISSUE TITLE
Trouble instantiating registered types.

### ISSUE THREAD

**Issue by Memhave** [jamesmh/coravel#107]
**Describe the bug**

.NET Core application throws when trying to instatiation implementation types, as per guide. 

- CoravelPro
- Using autofac to handle IoC
- `<TargetFramework>netcoreapp2.2</TargetFramework>`
- Service is registers like: `containerBuilder.RegisterType<ImageSynchronisationService>().As<IImageSynchronisationService>();`
- `IImageSynchronisationService` implements `IInvocable`. `ImageSynchronisationService` implements said `IImagesyncronisationService`
- Constructor
```
      public ImageSynchronisationService(
            ICaseImageService imageService,
            IConverter converter,
            ILogger<IImageSynchronisationService> logger)
        {
            _imageService = imageService ?? throw new ArgumentNullException(nameof(imageService));
            _converter = converter ?? throw new ArgumentNullException(nameof(converter));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }
```
- Interface
`    public interface IImageSynchronisationService : IInvocable  { }`
- `Invoke`: 
```
        public async Task Invoke()
        {
            await SynchroniseImagesAsync();
        }
```
- Transient added:
`services.AddTransient<IImageSynchronisationService>();`
- Scheduled as so:
```
 provider.UseScheduler(scheduler =>
                {
                    scheduler.Schedule<IImageSynchronisationService>()
                        .Daily()
                        .PreventOverlapping("ImageSynchronisationService");
                })
                .OnError(exception => logger.LogError("Coravel Scheduler threw: ", exception))
                .LogScheduledTaskProgress(logger);
```

- Exception:
```
{System.ArgumentException: Cannot instantiate implementation type '-.Services.Core.ScheduledServices.IImageSynchronisationService' for service type '-.Services.Core.ScheduledServices.IImageSynchronisationService'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.Populate(IEnumerable`1 descriptors)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory..ctor(IEnumerable`1 descriptors)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngineCallback callback)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CompiledServiceProviderEngine..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngineCallback callback)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at -.Program.Main(String[] args) in C:\Solutions\-\Program.cs:line 11}
```

**Affected Coravel Feature**
Scheduling, queueing not tested.

**Expected behaviour**
For the application to start successfully and have scheduled the job.

**Comment by jamesmh** [comment]
Coravel only supports the built-in .NET Core DI container 😥

**Comment by Memhave** [comment]
:( . Is there any planned support for other DI containers?

**Comment by jamesmh** [comment]
Not at the moment. 😥
