### ISSUE TITLE
InMemory Cache Index was outside the bounds of the array

### ISSUE THREAD

**Issue by heggi** [jamesmh/coravel#178]
**Describe the bug**
Has some code:
```
public async Task<int> GetDriverCabinId(int driverId)
{
    return await cache.RememberAsync($"driver_cabin_{driverId}", async() => {
        var request = new CoreService.Proto.GetDriverRequest {
            DriverId = driverId,
        };
        var driver = await coreDriverClient.GetDriverAsync(request);
        return driver.CabinId;
    }, TimeSpan.FromHours(1));
}
```

After about 230 elements are cached I got an Exception:
```
Index was outside the bounds of the array.
at System.Collections.Generic.HashSet`1.SetCapacity(Int32 newSize)
at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
at Coravel.Cache.InMemoryCache.RememberAsync[TResult](String key, Func`1 cacheFunc, TimeSpan expiresIn)
at ManagerApi.Repositories.CoreRepository.GetDriverCabinId(Int32 driverId)
```

**Affected Coravel Feature**
Cache

**Expected behaviour**
Cached "unlimited" elements without Exceptions

Coravel 3.6.1
.Net Core 3.1

**Comment by jamesmh** [comment]
Will check it out, thanks! 👍

**Comment by jamesmh** [comment]
Give Coravel 4.0.1 a try. Should do the trick 👍
