### ISSUE TITLE
RazorRenderer.FindView() throws System.InvalidOperationException: Unable to find view

### ISSUE THREAD

**Issue by Slaviusz** [jamesmh/coravel#197]
**Describe the bug**
When using Coravel Mailer from .Net Core 3.1 console project the Razor views required to render the mail body cannot be found.

**Affected Coravel Feature**
Mailer

**Expected behaviour**
Razor View successfuly rendered and mail sent.

```csharp
            var configuration = new ConfigurationBuilder()
                .SetBasePath(Path.Combine(AppContext.BaseDirectory))
                .AddJsonFile("appsettings.json", optional: false)
                .Build();

            Host = new HostBuilder()
                .ConfigureAppConfiguration((hostContext, confBuilder) =>
                {
                    confBuilder.SetBasePath(Directory.GetCurrentDirectory());
                    confBuilder.AddEnvironmentVariables(prefix: "PREFIX_");
                    confBuilder.AddCommandLine(args);
                    hostContext.Configuration = configuration;
                })
                .ConfigureServices((hostContext, services) =>
                {
                    services.AddSingleton<RazorRenderer>();
                    services.AddTransient<SwsLedPanelTabularReport>(); // Coravel IInvocable
                    services.AddMailer(configuration);
                    services.AddScheduler();
                })
                .Build();
```
```csharp
        public override void Build()
        {
            To(new MailRecipient(email: "redacted@redacted.xxx", name: "First Last"))
            .From("reports@redacted.xxx")
            .View("~/Views/Mail/TabularLedPanelReportMail.cshtml", _mailModel);

            foreach (var pathToAttachemnt in _mailModel.PathToAttachemnts)
            {
                var a = new Attachment()
                {
                    Bytes = File.ReadAllBytes(pathToAttachemnt),
                    Name = Path.GetFileName(pathToAttachemnt)
                };
                this.Attach(a);
            }
        }
```
```bash
$ tree bin/Debug/netcoreapp3.1/Views                                                                                                   
bin/Debug/netcoreapp3.1/Views
└── Mail
    └── TabularLedPanelReportMail.cshtml

1 directory, 1 file
```
```csharp
fail: Coravel.Scheduling.Schedule.Interfaces.IScheduler[0]
      A scheduled task threw an Exception: 
System.InvalidOperationException: Unable to find view '~/Views/Mail/TabularLedPanelReportMail.cshtml'. The following locations were searched:
~/Views/Mail/TabularLedPanelReportMail.cshtml
   at Coravel.Mailer.Mail.Renderers.RazorRenderer.FindView(ActionContext actionContext, String viewName)
   at Coravel.Mailer.Mail.Renderers.RazorRenderer.RenderViewToStringAsync[TModel](String viewName, TModel model)
   at Coravel.Mailer.Mail.Mailable`1.BuildMessage(RazorRenderer renderer, IMailer mailer)
   at Coravel.Mailer.Mail.Mailable`1.SendAsync(RazorRenderer renderer, IMailer mailer)
   at Coravel.Mailer.Mail.Mailers.FileLogMailer.SendAsync[T](Mailable`1 mailable)
   at mtis_scheduler.SwsLedPanelTabularReport.Invoke() in /home/slavius/source/repos/ebe_tis/mtis_scheduler/Program.cs:line 136
   at mtis_scheduler.SwsLedPanelTabularReport.Invoke() in /home/slavius/source/repos/ebe_tis/mtis_scheduler/Program.cs:line 147
   at Coravel.Scheduling.Schedule.Event.ScheduledEvent.InvokeScheduledEvent(CancellationToken cancellationToken)
   at Coravel.Scheduling.Schedule.Scheduler.<>c__DisplayClass26_0.<<InvokeEvent>g__Invoke|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Coravel.Scheduling.Schedule.Scheduler.InvokeEvent(ScheduledEvent scheduledEvent)
```

**Comment by jamesmh** [comment]
What version of the mailer package are you using?

**Comment by Slaviusz** [comment]
Sorry, forgot to mention. Coravel 4.0.2 and Coravel.Mailer 4.0.0

**Comment by Slaviusz** [comment]
Hi James, were you able to reproduce this issue or should I provide a mini repo?

**Comment by Slaviusz** [comment]
More info:

I did _strace_ of the run and there's absolutely no evidence the code is trying to search for a view on the disk. 
I tried using both relative and absolute path to the View (verifying the file on the disk exists, is not a sym/hard link and can be read by the user) with the same result.
```bash
[pid  4237] lstat("/home", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid  4237] lstat("/home/slavius", {st_mode=S_IFDIR|0755, st_size=12288, ...}) = 0
[pid  4237] lstat("/home/slavius/.dotnet", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid  4237] lstat("/home/slavius/.dotnet/shared", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid  4237] lstat("/home/slavius/.dotnet/shared/Microsoft.AspNetCore.App", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid  4237] lstat("/home/slavius/.dotnet/shared/Microsoft.AspNetCore.App/3.1.9", {st_mode=S_IFDIR|0755, st_size=12288, ...}) = 0
[pid  4237] stat("/home/slavius/.dotnet/shared/Microsoft.AspNetCore.App/3.1.9/System.IO.Pipelines.dll", {st_mode=S_IFREG|0644, st_size=144384, ...}) = 0
[pid  4237] openat(AT_FDCWD, "/home/slavius/.dotnet/shared/Microsoft.AspNetCore.App/3.1.9/System.IO.Pipelines.dll", O_RDONLY) = 185
[pid  4237] openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 186
[pid  4237] openat(AT_FDCWD, "/lib64/tls/Microsoft.DiaSymReader.Native.amd64.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid  4237] openat(AT_FDCWD, "/lib64/Microsoft.DiaSymReader.Native.amd64.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid  4237] openat(AT_FDCWD, "/usr/lib64/Microsoft.DiaSymReader.Native.amd64.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid  4237] openat(AT_FDCWD, "/home/slavius/.dotnet/shared/Microsoft.NETCore.App/3.1.9/Microsoft.DiaSymReader.Native.amd64.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid  4237] openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 186
[pid  4237] openat(AT_FDCWD, "/lib64/tls/Microsoft.DiaSymReader.Native.amd64.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid  4237] openat(AT_FDCWD, "/lib64/Microsoft.DiaSymReader.Native.amd64.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid  4237] openat(AT_FDCWD, "/usr/lib64/Microsoft.DiaSymReader.Native.amd64.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid  4237] openat(AT_FDCWD, "/home/slavius/.dotnet/shared/Microsoft.NETCore.App/3.1.9/Microsoft.DiaSymReader.Native.amd64.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid  4237] openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 186
[pid  4237] openat(AT_FDCWD, "/lib64/tls/Microsoft.DiaSymReader.Native.amd64.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid  4237] openat(AT_FDCWD, "/lib64/Microsoft.DiaSymReader.Native.amd64.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid  4237] openat(AT_FDCWD, "/usr/lib64/Microsoft.DiaSymReader.Native.amd64.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid  4237] openat(AT_FDCWD, "/home/slavius/.dotnet/shared/Microsoft.NETCore.App/3.1.9/Microsoft.DiaSymReader.Native.amd64.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid  4237] openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 186
[pid  4237] openat(AT_FDCWD, "/lib64/tls/Microsoft.DiaSymReader.Native.amd64.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid  4237] openat(AT_FDCWD, "/lib64/Microsoft.DiaSymReader.Native.amd64.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid  4237] openat(AT_FDCWD, "/usr/lib64/Microsoft.DiaSymReader.Native.amd64.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid  4237] openat(AT_FDCWD, "/home/slavius/.dotnet/shared/Microsoft.NETCore.App/3.1.9/Microsoft.DiaSymReader.Native.amd64.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid  4237] lstat("/home", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid  4237] lstat("/home/slavius", {st_mode=S_IFDIR|0755, st_size=12288, ...}) = 0
[pid  4237] lstat("/home/slavius/.dotnet", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid  4237] lstat("/home/slavius/.dotnet/shared", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid  4237] lstat("/home/slavius/.dotnet/shared/Microsoft.NETCore.App", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid  4237] lstat("/home/slavius/.dotnet/shared/Microsoft.NETCore.App/3.1.9", {st_mode=S_IFDIR|0755, st_size=12288, ...}) = 0
[pid  4237] stat("/home/slavius/.dotnet/shared/Microsoft.NETCore.App/3.1.9/System.Diagnostics.StackTrace.dll", {st_mode=S_IFREG|0644, st_size=27136, ...}) = 0
[pid  4237] openat(AT_FDCWD, "/home/slavius/.dotnet/shared/Microsoft.NETCore.App/3.1.9/System.Diagnostics.StackTrace.dll", O_RDONLY) = 186
[pid  4237] lstat("/home", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid  4237] lstat("/home/slavius", {st_mode=S_IFDIR|0755, st_size=12288, ...}) = 0
[pid  4237] lstat("/home/slavius/.dotnet", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid  4237] lstat("/home/slavius/.dotnet/shared", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid  4237] lstat("/home/slavius/.dotnet/shared/Microsoft.NETCore.App", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid  4237] lstat("/home/slavius/.dotnet/shared/Microsoft.NETCore.App/3.1.9", {st_mode=S_IFDIR|0755, st_size=12288, ...}) = 0
[pid  4237] stat("/home/slavius/.dotnet/shared/Microsoft.NETCore.App/3.1.9/System.Reflection.Metadata.dll", {st_mode=S_IFREG|0644, st_size=1076224, ...}) = 0
[pid  4237] openat(AT_FDCWD, "/home/slavius/.dotnet/shared/Microsoft.NETCore.App/3.1.9/System.Reflection.Metadata.dll", O_RDONLY) = 187
[pid  4237] stat("/home/slavius/source/repos/ebe_tis/mtis_scheduler/bin/Debug/netcoreapp3.1/Coravel.Mailer.dll", {st_mode=S_IFREG|0644, st_size=41472, ...}) = 0
[pid  4237] openat(AT_FDCWD, "/home/slavius/source/repos/ebe_tis/mtis_scheduler/bin/Debug/netcoreapp3.1/Coravel.Mailer.dll", O_RDONLY|O_CLOEXEC) = 188
[pid  4237] stat("/home/slavius/source/repos/ebe_tis/mtis_scheduler/bin/Debug/netcoreapp3.1/Coravel.Mailer.pdb", {st_mode=S_IFREG|0644, st_size=30436, ...}) = 0
[pid  4237] openat(AT_FDCWD, "/home/slavius/source/repos/ebe_tis/mtis_scheduler/bin/Debug/netcoreapp3.1/Coravel.Mailer.pdb", O_RDONLY|O_CLOEXEC) = 189
[pid  4237] lstat("/home", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid  4237] lstat("/home/slavius", {st_mode=S_IFDIR|0755, st_size=12288, ...}) = 0
[pid  4237] lstat("/home/slavius/.dotnet", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid  4237] lstat("/home/slavius/.dotnet/shared", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid  4237] lstat("/home/slavius/.dotnet/shared/Microsoft.NETCore.App", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid  4237] lstat("/home/slavius/.dotnet/shared/Microsoft.NETCore.App/3.1.9", {st_mode=S_IFDIR|0755, st_size=12288, ...}) = 0
[pid  4237] stat("/home/slavius/.dotnet/shared/Microsoft.NETCore.App/3.1.9/System.IO.MemoryMappedFiles.dll", {st_mode=S_IFREG|0644, st_size=59392, ...}) = 0
[pid  4237] openat(AT_FDCWD, "/home/slavius/.dotnet/shared/Microsoft.NETCore.App/3.1.9/System.IO.MemoryMappedFiles.dll", O_RDONLY) = 190
[pid  4237] stat("/home/slavius/.dotnet/shared/Microsoft.NETCore.App/3.1.9/System.Private.CoreLib.dll", {st_mode=S_IFREG|0644, st_size=9154048, ...}) = 0
[pid  4237] openat(AT_FDCWD, "/home/slavius/.dotnet/shared/Microsoft.NETCore.App/3.1.9/System.Private.CoreLib.dll", O_RDONLY|O_CLOEXEC) = 188
[pid  4237] stat("/home/slavius/.dotnet/shared/Microsoft.NETCore.App/3.1.9/System.Private.CoreLib.pdb", 0x14beb6b3f3f0) = -1 ENOENT (No such file or directory)
[pid  4237] lstat("/home/slavius/.dotnet/shared/Microsoft.NETCore.App/3.1.9/System.Private.CoreLib.pdb", 0x14beb6b3f400) = -1 ENOENT (No such file or directory)
[pid  4237] stat("/home/slavius/source/repos/ebe_tis/mtis_scheduler/bin/Debug/netcoreapp3.1/mtis_scheduler.dll", {st_mode=S_IFREG|0644, st_size=15872, ...}) = 0
[pid  4237] openat(AT_FDCWD, "/home/slavius/source/repos/ebe_tis/mtis_scheduler/bin/Debug/netcoreapp3.1/mtis_scheduler.dll", O_RDONLY|O_CLOEXEC) = 188
[pid  4237] stat("/home/slavius/source/repos/ebe_tis/mtis_scheduler/bin/Debug/netcoreapp3.1/mtis_scheduler.pdb", {st_mode=S_IFREG|0644, st_size=22068, ...}) = 0
[pid  4237] openat(AT_FDCWD, "/home/slavius/source/repos/ebe_tis/mtis_scheduler/bin/Debug/netcoreapp3.1/mtis_scheduler.pdb", O_RDONLY|O_CLOEXEC) = 191
[pid  4237] stat("/home/slavius/source/repos/ebe_tis/mtis_scheduler/bin/Debug/netcoreapp3.1/Coravel.dll", {st_mode=S_IFREG|0744, st_size=64512, ...}) = 0
[pid  4237] openat(AT_FDCWD, "/home/slavius/source/repos/ebe_tis/mtis_scheduler/bin/Debug/netcoreapp3.1/Coravel.dll", O_RDONLY|O_CLOEXEC) = 188
[pid  4237] stat("/home/slavius/source/repos/ebe_tis/mtis_scheduler/bin/Debug/netcoreapp3.1/Coravel.pdb", 0x14beb6b3f3f0) = -1 ENOENT (No such file or directory)
[pid  4237] lstat("/home/slavius/source/repos/ebe_tis/mtis_scheduler/bin/Debug/netcoreapp3.1/Coravel.pdb", 0x14beb6b3f400) = -1 ENOENT (No such file or directory)
[41mfail: Coravel.Scheduling.Schedule.Interfaces.IScheduler[0]
A scheduled task threw an Exception:
System.InvalidOperationException: Unable to find view '~/Views/Mail/TabularLedPanelReportMail.cshtml'. The following locations were searched:
~/Views/Mail/TabularLedPanelReportMail.cshtml
at Coravel.Mailer.Mail.Renderers.RazorRenderer.FindView(ActionContext actionContext, String viewName) in /home/slavius/source/repos/coravel/Src/Coravel.Mailer/Mail/Renderers/RazorRenderer.cs:line 104
at Coravel.Mailer.Mail.Renderers.RazorRenderer.RenderViewToStringAsync[TModel](String viewName, TModel model) in /home/slavius/source/repos/coravel/Src/Coravel.Mailer/Mail/Renderers/RazorRenderer.cs:line 49
at Coravel.Mailer.Mail.Mailable`1.BuildMessage(RazorRenderer renderer, IMailer mailer) in /home/slavius/source/repos/coravel/Src/Coravel.Mailer/Mail/Mailable.cs:line 199
at Coravel.Mailer.Mail.Mailable`1.SendAsync(RazorRenderer renderer, IMailer mailer) in /home/slavius/source/repos/coravel/Src/Coravel.Mailer/Mail/Mailable.cs:line 168
at Coravel.Mailer.Mail.Mailers.FileLogMailer.SendAsync[T](Mailable`1 mailable) in /home/slavius/source/repos/coravel/Src/Coravel.Mailer/Mail/Mailers/FileLogMailer.cs:line 54
at mtis_scheduler.SwsLedPanelTabularReport.Invoke() in /home/slavius/source/repos/ebe_tis/mtis_scheduler/Program.cs:line 119
at mtis_scheduler.SwsLedPanelTabularReport.Invoke() in /home/slavius/source/repos/ebe_tis/mtis_scheduler/Program.cs:line 130
at Coravel.Scheduling.Schedule.Event.ScheduledEvent.InvokeScheduledEvent(CancellationToken cancellationToken)
at Coravel.Scheduling.Schedule.Scheduler.<>c__DisplayClass26_0.<<InvokeEvent>g__Invoke|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at Coravel.Scheduling.Schedule.Scheduler.InvokeEvent(ScheduledEvent scheduledEvent)
```

**Comment by jamesmh** [comment]
Hey sry, a mini repo would def help. Haven't had a chance to look at this yet.

I have a couple quick questions:

1. Curious - does it work if you remove `services.AddSingleton<RazorRenderer>();` from the `ConfigureServices` method?

2. Also, just to verify, the view it's self is inside the console project, not another referenced project eh?

Otherwise, I'll have to do some digging. .NET Core 3 changed the way they were dealing with cshtml/razor files....always fun 😊

**Comment by Slaviusz** [comment]
Very simplistic repo here: https://github.com/Slaviusz/Coravel_Issue_197

I started with new console .Net Core 3.1 project:
```dotnet new console```
Then I followed a Microsoft tutorial to add _.NET Generic Host in ASP.NET Core_:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-3.1

Then added Coravel.Mailer on top. Results in the asme exception: Razor View cannot be found.

From all the debugging it seems to me the RazorViewEngine is not trying to load the view from disk. That means it is trying to find the compiled Razor View from the library. But that clearly requires some configuration I was not able to achieve.
I tried using ```IWebHost``` with proper RazorPages, Routing configuration instead of plain ```IHost``` with the same results.

I hope it helps somehow... :(

**Comment by jamesmh** [comment]
K so figured it out. Your views weren't being compiled into a dll. Coravel expects (ATM) that all views (`.cshtml`) are compiled at build time (which is why you don't see any file system I/O).

To get this to work you need to do two things:

1. Change the project's SDK to `Microsoft.NET.Sdk.Razor`
2. Add the following attribute in the csproj file:

```xml
<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AddRazorSupportForMvc>True</AddRazorSupportForMvc> 👈 ADD THIS ONE!
  </PropertyGroup>
```

Unfortunately, .NET Core 3.1 changed a bunch of stuff around razor rendering. It's been a real pain 😋

Adding support for file system "checking" could be added. I will need to update the docs too with this information.

Let me know if that works for you 👍

**Comment by Slaviusz** [comment]
Hi James,

  that worked like a charm! I already had the `<AddRazorSupportForMvc>True</AddRazorSupportForMvc>` in my .csproj file as I was testing several StackOverflow solutions. But it was the `Microsoft.NET.Sdk.Razor` that did the trick! After changing the SDK and recompiling the Views became part of the included library and Coravel as well as DI instantiated implementation of IRazorViewEngine can find them and render them.

Excellent work. Thanks a ton for your help and keep up the good work!
