### ISSUE TITLE
Styling issue on starting config

### ISSUE THREAD

**Issue by pkellner** [jamesmh/coravel#227]
I've never been a big fan of the css bundling Microsoft does with default asp.net pages so not really sure if this is related to that.  At any rate, I seem to be missing some style assets when I followed the installation directions here:

https://www.docs.pro.coravel.net/Installation/#installation-2

See my screen shot for the errors.

Also, do you want doc suggestions (not just bugs) as I run into things? (happy to create issues or do pull requests)  As a total newbe, I'm sure I'll see things you likely will not.  Also, I've done a ton of docs for Microsoft and they have schooled me well in not forgetting stuff so now I can't help myself when I see stuff Microsoft would complain to me about.

For example, in your ["That's it"](https://www.docs.pro.coravel.net/Installation/#that-s-it)  is not very satisfying.  I hunted around a little going forward in the docs and figured out that if I browse to http://localhost:5000/Coravel/Scheduling/ something good would happen.  As I'm not a complete newby in ASP.NET, I kind of expected something like that but not sure it would be obvious to others and it didn't seem that discoverable.

Maybe, instead of

That's It!
Phew! That was easy!

# What have we done?

Those are all the steps that are necessary to add Coravel Pro to your existing ASP.NET Core web app.  When your app starts, the Coravel service will run. If you used Entity Framework (EF) for persisting data used by Coravel, three new entities will be created in your EF data store. In addition, because you included the Coravel library in your app, you have access to several Coravel update and status web pages that will allow you to easily administer your Coravel Pro services. By default, these pages all run without any security so it's important that before you deploy your app to production that you secure those web pages. More information on how to do that can be found at the URL...

OK, I guess I am pretending you want suggestions though don't know for sure.  I've been told sometimes that unsolocited suggestions can also be thought of interference so please ignore and don't hold this against me if you are good as is :).

**Comment by jamesmh** [comment]
Hey again Peter!

I appreciate the feedback and suggestions and def. would love any help you feel led to provide 🎉 The Coravel Pro source code isn't open-source, so for now you can submit issues. Eventually, it might be worth open-sourcing the docs...

1. I love your suggestion about some more details around what to do after installing Coravel Pro, etc. 

2. As far as why the styles are missing...not sure lol. 
- What version of .NET / .NET Core are you using?
- What version of Coravel Pro are you using?
- Also, if you are able, could you provide the `Configure` and `ConfigureServices` methods for your `Startup.cs` file? (Remove any sensitive info, etc.)

Thanks!

**Comment by pkellner** [comment]
.net core 5

  public void ConfigureServices(IServiceCollection services)
        {
            services.AddRazorPages().AddNewtonsoftJson();
            
            
            // services.AddDbContext<ApplicationDbContext>(options =>
            //     options.UseSqlite(
            //         Configuration.GetConnectionString("DefaultConnection")));
            // services.AddDatabaseDeveloperPageExceptionFilter();
            
            // MYSQL
            services.AddDbContext<ApplicationDbContext>(
                dbContextOptions => dbContextOptions.UseMySql("server=localhost;user=power;password=Pass@Word!;database=powerdata",
                    new MySqlServerVersion(new Version(8, 0, 22))));
            



            services.AddDatabaseDeveloperPageExceptionFilter();

            services.AddDefaultIdentity<ApplicationUser>(options => options.SignIn.RequireConfirmedAccount = true)
                .AddEntityFrameworkStores<ApplicationDbContext>();
            services.AddControllersWithViews();
            
            services.AddCoravelPro(typeof(ApplicationDbContext));
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseMigrationsEndPoint();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            //app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();

            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
                endpoints.MapRazorPages();
            });
        }



![coravel-prob2](https://user-images.githubusercontent.com/241170/120262392-7caecc00-c24e-11eb-978e-209868156ee9.png)

**Comment by jamesmh** [comment]
Hey Peter, I'll have a look at this in the coming days. I'll try to re-produce etc. Might be something to do with .NET 5 🤷‍♂️

**Comment by jamesmh** [comment]
K, so in `ConfigureServices` add `services.AddRazorPages().AddNewtonsoftJson();` after the call to `AddControllersWithViews`.

Then, in `Configure` add `app.UseCoravelPro();` at the end.

Let me know if that fixes things 👍

**Comment by igsuffolk** [comment]
Did that fix the issue?
I am having the same problem with webpack-bundle.js. 
Running from Visual Studio 2022

New "ASP.NET Core Web App (Razor Pages)"
Coravel Pro (5.2.2)

![Capture](https://github.com/jamesmh/coravel/assets/74656705/07fb3fe8-d24d-4cbc-a8f9-eff32bc7b88f)


program.cs

var builder = WebApplication.CreateBuilder(args);

var config = new ConfigurationBuilder()
       .AddJsonFile("appsettings.json", optional: false)
       .Build();

// Add services to the container.

builder.Services.AddRazorPages().AddNewtonsoftJson();

builder.Services.AddDbContext<JobManager.EntityContext.AngliaDbContext>(options =>
{
    options.UseSqlServer(config.GetConnectionString("AngliaDB"));
    if (builder.Environment.IsDevelopment())
        options.EnableSensitiveDataLogging();
});


builder.Services.AddCoravelPro(typeof(AngliaDbContext));

var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseRouting();

app.UseAuthorization();

app.UseEndpoints(endpoints =>
{
    endpoints.MapRazorPages();
});

app.Run();

app.UseCoravelPro();

**Comment by gently1** [comment]
@igsuffolk app.UseCoravalPro() before app.Run()

**Comment by igsuffolk** [comment]
@gently1 Thanks. 
Did a cleanup a while ago so restarted with a new .Net8 project.
Migrations etc done.
Start the project and get this error:

System.Reflection.ReflectionTypeLoadException
  HResult=0x80131602
  Message=Unable to load one or more of the requested types.
Could not load type 'SqlGuidCaster' from assembly 'Microsoft.Data.SqlClient, Version=5.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5' because it contains an object field at offset 0 that is incorrectly aligned or overlapped by a non-object field.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes() in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/RuntimeModule.cs:line 447
   at Coravel.Pro.Features.Jobs.Services.InvocablesCollectionService.AddInvocablesFromAssembly(Assembly assembly)
   at Coravel.Pro.ServiceRegistration.AssignAllRegisteredJobs(IApplicationBuilder app)
   at Coravel.Pro.ServiceRegistration.UseCoravelPro(IApplicationBuilder app)


Apparently already reported here:
[](https://github.com/jamesmh/coravelpro/issues/51)
and here
[](https://github.com/dotnet/SqlClient/issues/1930)

Looks like the issue is with  Microsoft.EntityFrameworkCore.SqlServer 8.0.7 which referencese Microsoft.Data.SqlClient 5.1.5
